LLVM_ARCHTYPE and RUSTFLAGS modification for right rustc target
1.Even though the Cortex-M55 is technically an ARMv8.1-M architecture, the Rust compiler ecosystem generally uses the thumbv8m.main
Target error log:
error: failed to run `rustc` to learn about target-specific information
Caused by:
error: error loading target specification: could not find specification for target "thumbv8.1m.main-nuttx-eabihf"
= help: run `rustc --print target-list` for a list of built-in targets

2.RUSTFLAGS:target :thumbv8m.main+dsp+mve.fp+fp.dp-none-eabihf error

Change-Id: I7b1dbd4b2c77bcbfb373be31030907c6fde2c207